### ISSUE TITLE
Set font-display rule to block to make Lighthouse happy

### ISSUE THREAD

**Issue by oleksandrzaiats** [FortAwesome/wordpress-fontawesome#108]
Hi!
It seems that the issue (https://github.com/FortAwesome/Font-Awesome/issues/16077 that seem to be fixed in the mail repo) still persists when using Font Awesome Wordpress plugin (https://wordpress.org/plugins/font-awesome/). I am using that plugin (with the latest version of font - 5.15.2) and I get `Leverage the font-display CSS feature...` in the report from Lighthouse. This warning displays fonts from urls like https://use.fontawesome.com/releases/v5.15.2/webfonts/fa-** as affected.
I checked the code of that plugin and it seems like there is no font-display set. I did not find any issue tracking for that plugin so I decided to write here.
Is it possible to fix that? Thanks!

**Comment by mlwilkerson** [comment]
closed by #110

**Comment by mlwilkerson** [comment]
@oleksandrzaiats this has been released in 4.0.0-rc22 (forgot to include it in the changelog!)

**Comment by oleksandrzaiats** [comment]
@mlwilkerson Thanks! I have updated the plugin and can confirm that the issue is solved.
