### ISSUE TITLE
Icon chooser in ACF not working

### ISSUE THREAD

**Issue by R3dRidle** [FortAwesome/wordpress-fontawesome#147]
Hello,

Most of the issues seem to be fixed. But when I try to click on the Icon Chooser button within ACF WYSIWYG field nothing happens.
No console error or whatsoever.

The ACF WYSIWYG is inside a repeater field.

Hope you guys can figure this out.

Kind regards
Dennis

**Comment by mlwilkerson** [comment]
Thanks for the report @R3dRidle. I'm investigating.

**Comment by mlwilkerson** [comment]
@R3dRidle would you be willing and able to try [this pre-release 4.0.0-rc2 zip](https://github.com/FortAwesome/wordpress-fontawesome/releases/download/4.0.3-rc2/font-awesome.zip) and let me know if it solves the problem with the ACF integration. It's working in my environment.

**Comment by R3dRidle** [comment]
@mlwilkerson 
That seems to work perfectly ! :)

**Comment by mlwilkerson** [comment]
@R3dRidle Version 4.0.3 has been released with the fix for this issue.

**Comment by R3dRidle** [comment]
Great!
