### ISSUE TITLE
FA WP plugin 4.1.0 with WP 5.9 crash on update

### ISSUE THREAD

**Issue by TravelingTartar** [FortAwesome/wordpress-fontawesome#159]
Upon install of 4.1.0, on a WP 5.9 site, the site blocked. Went in via recovery mode, deactivated and reactivated the plugin and it worked. Repeated and still had same problem. So now works, but only because I went in via recovery mode. Hope this helps.

**Comment by mlwilkerson** [comment]
Note to Self:

Initially, it seems mostly likely that the plugin upgrade triggered an excessive load on the API server, and blocking network requests to the server resulted in blocked page loads.

A possible solution is to avoid refreshing release metadata in `try_upgrade()`, unless necessary. And, thinking through various scenarios, it shouldn't be necessary, even when upgrading the data schema of the `font-awesome` or `font-awesome-releases` options schemas.

**Comment by mlwilkerson** [comment]
@TravelingTartar It might also help to know whether you see any other "registered" themes or plugins on the Troubleshoot tab in this plugin's settings page.

**Comment by TravelingTartar** [comment]
Hi.
Nope, none, as per attached screenshot.

**Comment by mlwilkerson** [comment]
@TravelingTartar your screenshot didn't come through with that attachment. But that's OK. I can work without it.

**Comment by mlwilkerson** [comment]
I just release version 4.1.1 of the plugin that has simplified upgrade logic. In particular, it makes no network requests to refresh metadata from the API server upon upgrade. I think this is most likely the issue.

NOTE: I've not seen any problems with upgrading to 4.1.0 under WP 5.9. So I don't think there's an issue with WP 5.9 compatibility. If something else comes up for someone else, of course, we'll get a new investigation going on a new issue.

Thanks again for the report.
