### ISSUE TITLE
Using ${var} in strings is deprecated

### ISSUE THREAD

**Issue by lifeinthegrid** [FortAwesome/wordpress-fontawesome#201]
Hi Guys,

Thanks for the plugin!    Getting allot of deprecation messages in PHP 8 with older string variable lookups.

Example of one of the messages.

Deprecated: Using ${var} in strings is deprecated, use {$var} instead in \wp-content\plugins\font-awesome\includes\class-fontawesome.php on line 1945

Should be a super simple fix just switch it from ${var} to {$var}

Thanks much!

**Comment by mlwilkerson** [comment]
Thanks for the report!

**Comment by masteradhoc** [comment]
@mlwilkerson can you check my PR? :) would be great to get a new version soon

**Comment by mlwilkerson** [comment]
@masteradhoc and  @lifeinthegrid  This fix was released just now in 4.4.0.

I also discovered and fixed several more of the same kind of deprecation warnings for php 8.2 in PR #205
