### ISSUE TITLE
Not available in Site Editor

### ISSUE THREAD

**Issue by warudin** [FortAwesome/wordpress-fontawesome#208]
The Font Awesome Icon-picker in the "popover" toolbar is only available in the Post Editor. Can it be made available in the Site Editor as well?

This is a screenshot of a page in the **Post Editor** (the Font Awesome Icon-picker is **available** in the toolbar):
![Scherm­afbeelding 2023-08-31 om 10 36 01](https://github.com/FortAwesome/wordpress-fontawesome/assets/1815847/d3b3913f-a69d-4b91-b667-631980a237dc)

This is a screenshot of that same page in the **Site Editor** (the picker is **unavailable** in the toolbar):
![Scherm­afbeelding 2023-08-31 om 10 35 41](https://github.com/FortAwesome/wordpress-fontawesome/assets/1815847/3d552d53-49af-4b99-8f6a-481aabdc91e7)

**Comment by mlwilkerson** [comment]
@warudin thanks for the request. I do expect to see this feature in a future version of the plugin.
