### ISSUE TITLE
Functionality to get all available icons

### ISSUE THREAD

**Issue by b8kkyn** [FortAwesome/wordpress-fontawesome#50]
I'm writing plugin right now. There will be icon picker where Website Admin can select Font Awesome icons for use.

This plugin already loads corresponding version of Font Awesome which meets clients' requirements (with pro icons option where Website Admin can enable it).

So, wouldn't it be great if there was a method to list all the available icons with plugin's current settings, whether svg or webfont method, free or pro icons? Similar to `get_available_versions()`.

But this method must return full css classes such as `far fa-address-card`, `fas fa-ad` etc. Not just icon names but `fas`, `far`, `fal`, `fad`, `fab` indicating exact style.

**Comment by mlwilkerson** [comment]
Thank you. Yes, I do imagine that a future release of this plugin will provide expanded metadata for all icons, similar to what you've described.
