### ISSUE TITLE
Pseudo-Elements Error

### ISSUE THREAD

**Issue by hirenshah** [FortAwesome/wordpress-fontawesome#82]
Just noticed that when you are on the Font Awesome Settings page, under the section labelled Technology, if you do the following:
1) Select SVG
2) Make sure _"Enable CSS Pseudo-elements with SVG"_ is unticked
3) Select Web Font (do all this without Saving Changes)
4) Save Changes

It results in the following error being displayed:
_Pseudo-elements cannot be disabled with webfont technology._

![Annotation 2020-05-18 184046](https://user-images.githubusercontent.com/418112/82243224-2159b680-9937-11ea-9e6e-9ceb873b2216.png)

Looks like your form validation isn't quite right.  Everything appears to save fine though.

If you repeat what I mentioned above, but add an extra step, you don't see that validation error:
1) Select SVG
2) Make sure _"Enable CSS Pseudo-elements with SVG"_ is unticked
3) **Save Changes**  _<-- extra step_
4) Select Web Font
5) Save Changes

**Comment by mlwilkerson** [comment]
@hirenshah good catch. I think I know what's going on here. Should be an easy fix.

**Comment by hirenshah** [comment]
@mlwilkerson I can't take any credit for spotting this... it was literally a case of "my finger slipped" lol.

I don't think it is a big deal as it appears to only be a cosmetic issue :)
