### ISSUE TITLE
Make the top level admin menu item a sub item

### ISSUE THREAD

**Issue by first-wgrt** [FortAwesome/wordpress-fontawesome#92]
The Font Awesome plugin adds a top level item to the WordPress admin menu. This menu gets cluttered easily, especially when one installs many plugins which all add top level items to it. I believe the need for such a top level menu item should therefore be carefully considered. Settings pages that need to be visited very frequently should be on the top level. Pages that are visited rarely should, IMHO, be sub pages.

Most of the time, I only visit the Font Awesome menu page once: after I activate the plugin. When everything is set up correctly, I never visit it again. That is why I think it should be a sub page of the 'Settings' page.

I am aware that this is a minor issue, but every time I install this plugin, it comes to my mind again, so I thought I'd start a discussion about it. I'd be happy to submit a PR.

**Comment by mlwilkerson** [comment]
@first-wgrt yeah, that makes sense. This was originally a sub-menu, but we promoted recently. It does make sense to push it back down into a sub-menu, for just the reasons you cite. PR welcome 👍

**Comment by first-wgrt** [comment]
@mlwilkerson Created PR #93. It's my first open source contribution, so I was not fully sure how to do it, but I believe I figured it out 😉
